---
title       : My First slidify
subtitle    : This is my first experience on creating deck with slidify.
author      : Yutaka Koga
job         : TBD
framework   : io2012        # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : solarized_light      # 
widgets     : [bootstrap, quiz]            # {mathjax, quiz, bootstrap}
mode        : selfcontained # {standalone, draft}
knit        : slidify::knit2slides
ext_widgets: {rCharts: [libraries/morris, libraries/nvd3]}

--- &radio
## Interactive quiz.
What is 1 + 1 ?  

1. 1  
2. _2_  
3. 3  
4. 4  

*** .hint

This is a hint.

*** .explanation

This is an explanation.

---

## Interactive chart with rCharts
```{r echo = FALSE, results = 'asis', cache=FALSE}
require(rCharts)
haireye = as.data.frame(HairEyeColor)
n1 <- nPlot(Freq ~ Hair, group = 'Eye', type = 'multiBarChart', 
            data = subset(haireye, Sex == 'Male')
)
n1$print('chart1')
```

---

## Time Series chart.
```{r cache=FALSE}
library(knitr)
read_chunk('./chap2-4.R')
```

```{r plot-return, results='asis', cache=FALSE, echo=FALSE}
```

--- 

## Time Series chart.
```{r plot-price, results='asis', cache=FALSE, echo=FALSE}
```


---


## Analyze mean and variance for X and Y
```{r mean-and-var-xy, results='asis', cache=FALSE, echo=TRUE}
```

```{r, cache=FALSE, echo=FALSE}
print('--- head(df_stat) ---')
head(df_stat)
```
