morris:
  css: css/morris.css
  jshead: 
    - js/jquery-1.8.2.min.js
    - js/raphael-2.1.0.min.js
    - js/morris.min.js
  cdn:
    css: "//cdnjs.cloudflare.com/ajax/libs/morris.js/0.5.1/morris.css"
    jshead:
      - //ajax.googleapis.com/ajax/libs/jquery/1.9.0/jquery.min.js
      - //cdnjs.cloudflare.com/ajax/libs/raphael/2.1.0/raphael-min.js
      - //cdnjs.cloudflare.com/ajax/libs/morris.js/0.5.1/morris.min.js

